/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Encrypts content using AES-256-GCM with a password.
 *
 * # Arguments
 * * `content` - The content to encrypt
 * * `password` - The password to use for encryption
 *
 * # Returns
 * * `Result<String, napi::Error>` - Hex-encoded encrypted content or error
 */
export declare function encrypt(content: string, password: string): string
/**
 * Decrypts previously encrypted content.
 *
 * # Arguments
 * * `encrypted_content` - The hex-encoded encrypted content
 * * `password` - The password used for encryption
 *
 * # Returns
 * * `Result<String, napi::Error>` - Decrypted content or error
 */
export declare function decrypt(encryptedContent: string, password: string): string
